### ISSUE TITLE
[Feature request] Windows support

### ISSUE THREAD

**Issue by Kristinita** [dtao/SublimeBucket#1]
Currently your package only for Linux and macOS users, but many Windows users use BitBucket too. It would be nice, if you add Windows support.

Thanks.

**Comment by dtao** [comment]
Good news! I've updated the plugin to work on Windows. It should be installable once [this PR to the Package Control repository](https://github.com/wbond/package_control_channel/pull/6193) is merged.

**Comment by dtao** [comment]
Good news, [it's merged](https://github.com/wbond/package_control_channel/pull/6193)! I _think_ that means you should be able to install this plugin in Windows now.

This probably goes without saying, but: you will need to have git and mercurial installed, respectively, for this plugin's features to work.
